import cv2
DISPLAY_ALL_SOURCE_CODE = False
DRAW_DENSE_MAP = False
WRITE_README = True

DRAW_FILENAME_EXTENSION_LIST = ["py", "md"]
DIRECTORY_IGNORED = [".git", ".idea", "__pycache__", ".ipynb_checkpoints"]

FILE_COLOR = (125,0,0)
DIR_COLOR = (0xff,0xd4,0)
FILE_PACK_COLOR = (224,255,255)  # cyan
TITLE_COLOR = (180, 180, 187)


WIDTH = 200 # 가로 길이를 기준으로 비율을 정하자
STANDARD_HEIGHT = int(1.2*WIDTH)

WB_UPPER_PADDING = int(STANDARD_HEIGHT/10)  # white board 모서리 부분의 패딩
WB_LEFT_PADDING = int(WIDTH/10)

WB_WIDTH_BETWEEN_CELLS = int(WIDTH * 0.4)  # 셀과 셀 사이의 수평간격
WB_HEIGHT_BETWEEN_CELLS = int(STANDARD_HEIGHT * 0.2)

TITLE_WIDTH = int(WIDTH)  # 셀의 제목 가로길이
TITLE_HEIGHT = int(STANDARD_HEIGHT*0.2)  # 셀의 제목 세로 길이
TITLE_FONT = 'malgun.ttf'  # 셀의 제목 글자 폰트
TITLE_FONT_SIZE = int(WIDTH*0.1)  # 셀의 제목 글자 크기

BODY_FONT = 'malgun.ttf'  # 셀의 본문 글자 폰트
BODY_FONT_SIZE = int(WIDTH*0.08)  # 셀의 본문 글자 크기

BODY_UPPER_PADDING = int(STANDARD_HEIGHT * 0.05)
BODY_LEFT_PADDING = int(WIDTH*0.01)
BODY_UNDERLINE_PADDING = int(BODY_FONT_SIZE*1.5)

TITLE_TEXT_UPPER_PADDING = int(STANDARD_HEIGHT * 0.008)  # sx,sy 로부터 title의 글자의 거리
TITLE_TEXT_LEFT_PADDING = int(WIDTH * 0.05)
TITLE_TEXT_MAXLINE = 2
TITLE_TEXT_MAXLEN = int(WIDTH/TITLE_FONT_SIZE*1.8)  # 15개
TITLE_HEIGHT_BETWEEN_TEXT = int(TITLE_FONT_SIZE)

HEIGHT_BETWEEN_BODY_TEXTS = int(BODY_FONT_SIZE/2)  # 본문 글자와 글자 사이의 거리
BODY_HEIGHT_BETWEEN_TEXT = BODY_FONT_SIZE
BODY_TEXT_INTERVAL = int(BODY_FONT_SIZE + BODY_HEIGHT_BETWEEN_TEXT)
BODY_TEXT_MAXLINE = 1
BODY_TEXT_MAXLEN = int(WIDTH/BODY_FONT_SIZE*1.9)  # 20개

LINE_PADDING_X = int(WIDTH * 0)  # sx, sy로 부터 선의 시작까지의 거리
LINE_PADDING_Y = int(TITLE_HEIGHT*0.5)


